# Generated by Django 2.0 on 2018-01-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ask_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bit_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='close_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_size',
            field=models.IntegerField(default=0),
        ),
    ]
